### PR TITLE
Starting implementation of CreateDevice

### PR DESCRIPTION
**Pull request by michelececcacci**

### CODE REVIEW

**Comment by aleemont1** [comment]
I'm confused about this PR. What is its purpose? What should I watch? I see changes in the View, in the Controller eccetera.
As for the title the relevant part is the CreateDevice, which seems to use an `enum`, I thought we had discarded that idea (?). Also, javadoc is missing, please use more explicit comments expecially for methods whose scope and purpose aren't so obvious at first sight.

Also, is that `switch() case:` the only option we have? We have been writing ultra-high quality code the whole time, that `switch() case:`, idk i don't like it too much.
In the end, the code does not look so mantainable to me, we'll have to add a new entry for every device we'll create, with a prefixed constructor, which means no customization at all for the end-user. IDK, I think it needs lots of work, if I misunderstood the purpose of this PR I'm eager to ear from you.

**Comment by michelececcacci** [comment]
>Also, is that switch() case: the only option we have?

The thing is, we don't really want the user to know about all possible type of non-instantiable devices (or devices that can basically be accessed through a factory)

**Comment by aleemont1** [comment]
i think we can use reflection for this purpose, it's going to be more elaborate but it looks MUCH more elegant and maintainable to me. We'll need to follow very strict package structure rules, but I think it's worth it.

**Comment by smagnaniuni** [comment]
@aleemont1

The other proposal was using the command pattern

From the controller we return a list of commands for the creation of the different devices.
From the view the command will be selected and sent back to the controller.
The command could encapsulate other data such as the string.

There was a discussion but I don't remember what the problem with this was

**Comment by michelececcacci** [comment]
>The other proposal was using the command pattern

btw, i'm not totally opposed to this. I'll also try to submit a PR using command pattern.

**Comment by michelececcacci** [comment]
@aleemont1 I took a look at reflection, and tried to think about what you told me. Not sure if i understand it correctly, but basically your approach would be to scan the `model` subdirectory looking for final classes, and then mapping each of them to a button that will instantiate them?

**Pull request closed without merging**
