### PR TITLE
View

### PR DESCRIPTION
**Pull request by michelececcacci**
@smagnaniuni need a review on the last commit (i think it could be implemented in a better way, but not sure how). Everything is explained in `JFXDeviceView`. The downside is that we would need every to extend `VBox`. It's a big limitation, but it makes the codebase much cleaner. everything else can be merged, so if you think it's not appropriate, i'll just drop the last commit, or refactor it

### CODE REVIEW

**Comment by smagnaniuni** [comment]
You can just extend `Node`

**Comment by michelececcacci** [comment]
> You can just extend `Node`

that's the thing, `Node` has no `GetChildren` method, i need a `Pane` for that

**Comment by smagnaniuni** [comment]
Then extend `Pane`

**Comment by michelececcacci** [comment]
> Then extend `Pane`

If i just extend Pane, everything overlaps and it looks really bad.

**Review by smagnaniuni — APPROVED** [review]

**Pull request merged**
