### PR TITLE
Add SimManager and corresponding view

### PR DESCRIPTION
**Pull request by smagnaniuni**
Swing view will probably be replaced with a javafx component since it seems that the two error handlers conflict and generate this warning.
```
(java:3175569): Gdk-WARNING **: 13:47:04.652: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
```

### CODE REVIEW

**Comment by michelececcacci** [comment]
Looks fine (provided the view gets later ported to javafx). Honestly this isn't really my domain, so i won't be able to catch many errors. Not really sure why getDevices should return a viewManager, but that's probably a leftover

**Comment by smagnaniuni** [comment]
> Looks fine (provided the view gets later ported to javafx). Honestly this isn't really my domain, so i won't be able to catch many errors. Not really sure why getDevices should return a viewManager, but that's probably a leftover

Ported to fx :)
Not sure what you mean with the getDevices, I didn't touch it and it does not seem to be return a ViewManager?

**Comment by michelececcacci** [comment]
>Not sure what you mean with the getDevices, I didn't touch it and it does not seem to be return a ViewManager?

nevermind, my bad. LGTM

**Comment by michelececcacci** [comment]
>Should I wait for refactor to be merged before merging?

I don't really know. I think it would be the best option, but i'm not totally sure

**Comment by aleemont1** [comment]
So this is going to be the mainLoop' Should I drop my PR?
This looks a better approach.

**Comment by smagnaniuni** [comment]
Well the loop "runnable" itself I did is kind of a first draft at the moment, but I think the infrastructure behind it should be like this.
The loop itself can always be reworked by creating another class which receives the SimManager as a reference, so that it can ask the simulated step period.

So like, for example in the constructor of `SimManager`

```java
this.loopRunnable = new SimLoop(this)
```

And then the SimLoop extends Runnable

```java
public class SimLoop extends Runnable {
...
  public SimLoop(final SimManager simManager) {
  ...
  }
...
}
```

In terms of the discreteObjects, we have two choices at the moment:
- call the updateTick of the devices from the controller updateTick (loop each device and check if it's an instanceof DiscreteObject, not a superb way to do it but it should work)
- use the observer pattern in the specific adding/removal of a device, so that the loop can keep track of them and call their updateTick

If you have other ideas feel free to add otherwise I feel comfortable on continuing to work on this.

**Comment by aleemont1** [comment]
> If you have other ideas feel free to add otherwise I feel comfortable on continuing to work on this.

Keep going then, if something pops to my mind i'll let you know.
CI'll focus on view now then.

**Pull request merged**
