### PR TITLE
[controller] refactor DeviceManager by separating logic and view methods

### PR DESCRIPTION
**Pull request by smagnaniuni**
Also the methods `toggleDevice` and `removeAllDevices` might be a bit redundant but fine to keep.

### CODE REVIEW

**Comment by smagnaniuni** [comment]
If we use the command pattern also for toggling, updating, and removing all devices, those methods should be moved from the observer to the logic interface

**Comment by michelececcacci** [comment]
>Also the methods toggleDevice and removeAllDevices might be a bit redundant but fine to keep.

we can take them off, no problem

**Review by michelececcacci — APPROVED** [review]
LGTM

**Comment by michelececcacci** [comment]
everything else looks good to me

**Pull request merged**
