### PR TITLE
View

### PR DESCRIPTION
**Pull request by michelececcacci**

### CODE REVIEW

**Comment by smagnaniuni** [comment]
This does not update the view of the device (sensor eg. thermometer)

**Comment by michelececcacci** [comment]
> This does not update the view of the device (sensor eg. thermometer)

True. We could use `instanceof` for that, but i'm open to suggestionsdo you have any other ideas?

**Comment by smagnaniuni** [comment]
I rather call the view update on the sensor devices in the `Controller::updateTick` than sending an environment object.

**Comment by michelececcacci** [comment]
> I rather call the view update on the sensor devices in the `Controller::updateTick` than sending an environment object.

This would only work with a single `Environment` though, right? and we would need to pass a reference. Not opposed to this, just trying to disambiguate.

**Comment by smagnaniuni** [comment]
You don't have to touch `Environment` at all, actually sending the environment object to the view is a mvc violation.

In the updateTick just stream through the devices, find the instanceof of the particular device, and then call viewManager.update with that device id/state.

**Comment by michelececcacci** [comment]
You don't have to touch Environment at all, actually sending the environment object to the view is a mvc violation.
>
In the updateTick just stream through the devices, find the instanceof of the particular device, and then call viewManager.update with that device id/state.

I like it. should i do it myself, or do you want to take care of it?

**Comment by michelececcacci** [comment]
> You don't have to touch `Environment` at all, actually sending the environment object to the view is a mvc violation.
> 
> In the updateTick just stream through the devices, find the instanceof of the particular device, and then call viewManager.update with that device id/state.

Sounds good to me, i'll start implementing it right now.

**Review by smagnaniuni — APPROVED** [review]

**Pull request merged**
