### PR TITLE
[POWERED] First PoweredDevice interface

### PR DESCRIPTION
**Pull request by aleemont1**
Just a rough idea to start.

### CODE REVIEW

**Comment by aleemont1** [comment]
@smagnaniuni @michelececcacci I know it needs a lot of work, but as a starting point is it good enough?
My idea right now is to implement this Interface in a PoweredDeviceImpl, which is going to be extended by the various devices, does it seem good?

**Review by smagnaniuni — COMMENTED** [review]
istant -> instant

Not sure why the PoweredDevice interface would extend DiscreteObject
Devices should not extend PoweredDeviceImpl, they should either implement the interface or have an internal component for the power

**Comment by aleemont1** [comment]
> istant -> instant
> 
> Not sure why the PoweredDevice interface would extend DiscreteObject Devices should not extend PoweredDeviceImpl, they should either implement the interface or have an internal component for the power

PoweredDevices all need to update their state in terms of power consumption, I thought I could extend the DiscreteObject, overriding updateTick with an empty method which should be then implemented in the actual device class, but maybe I'm interpreting this wrong. 

Do you have any suggestion? What do you mean with an "Internal Component"?

**Comment by smagnaniuni** [comment]
Use either strategy or component pattern.
Single devices should not extend PoweredDeviceImpl.

Extension should only be used sparingly (eg. with abstract classes).
Classes can't extend multiple classes, but they can implement multiple interfaces.
Plus it would lead to all sorts of weird behavior, devices being able to override methods or outright prohibited from doing so by the class that is being extended, there is clearly a conflict here.

As for the interface extension, it's more conceptual but being a powered device and a discrete object seems like two distinct concepts to me.
If a device requires time to update internal implementation details it should implement DiscreteObject.
If a device requires to deal with power consumption it should implement PoweredDevice.
Also the current methods are instantaneous values.
Otherwise Device itself should extend DiscreteObject.
But I'll review this part again later.

**Comment by aleemont1** [comment]
> Use either strategy or ~component~ (it was either composite or decorator, I don't remember atm) pattern. Single devices should not extend PoweredDeviceImpl.
> 
> Extension should only be used sparingly (eg. with abstract classes). Classes can't extend multiple classes, but they can implement multiple interfaces. Plus it would lead to all sorts of weird behavior, devices being able to override methods or outright prohibited from doing so by the class that is being extended, there is clearly a conflict here.
> 
> As for the interface extension, it's more conceptual but being a powered device and a discrete object seems like two distinct concepts to me. If a device requires time to update internal implementation details it should implement DiscreteObject. If a device requires to deal with power consumption it should implement PoweredDevice. Also the current methods are instantaneous values. Otherwise Device itself should extend DiscreteObject. But I'll review this part again later.

Got it, sorry but I was just mixing things up, look at the new interface, I removed the implementation, and it doesn't extend DiscreteObject. Have a look at #95 too, and lmk if I finally interpreted it in the right way.

**Pull request closed without merging**
